@echo off

REM Clone the repository using Git
git clone https://github.com/FeltMacaroon389/Snake.py

REM Change working directory
cd Snake.py

REM Install Pyinstaller
pip3 install Pyinstaller

REM Use Pyinstaller to compile the Snake.py file into a single executable (.exe)
pyinstaller --onefile Snake.py

REM Move the executable into the Snake.py directory
move \dist\Snake.exe .

REM Delete unnecessary files
RD /S /Q "build"
del Snake.spec
del LICENSE
del README.md
del requirements.txt
del Snake.py
del AutoInstall.sh

REM Rename the dist folder generated by Pyinstaller
ren dist Executable

REM Change working directory
cd Executable

REM Ask if the user wants to open the Snake.exe file
set /p open_snake=Do you want to open the newly created Snake game? (Y/N):
if /i "%open_snake%"=="Y" (
    start Snake.exe
) else (
    echo Exiting...
)
